name: weekly release

on:
  schedule:
    - cron: "0 10 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "::set-output name=dir::$(yarn cache dir)"
        - name: Use yarn cache
          uses: actions/cache@v3
          with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-
        - name: run
          run: |
            yarn install --frozen-lockfile
            yarn test
  publish_release:
    # if: github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'release candidate') && github.event.label.name == 'approve release'
    runs-on: ubuntu-latest
    # env:
    #   CHANGELOG_PATH: /tmp/CHANGELOG.md
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          # registry-url: 'https://registry.npmjs.org'
      - name: git config
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - run: yarn install --frozen-lockfile
      - run: yarn release
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: echo NEW_TAG=$(git describe) >> $GITHUB_ENV
      - run: git push origin $NEW_TAG
      - run: npx ts-node ./scripts/getLatestChangelog.ts > ${{ env.CHANGELOG_PATH }}
      - name: create release on GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: ${{ env.NEW_TAG }}
          body_path: ${{ env.CHANGELOG_PATH }}
          commitish: master
          prerelease: ${{ env.IS_PRERELEASE }}
      - name: close issue
        uses: peter-evans/close-issue@v2
      - name: delete branch
        run: git push origin :release-candidate
      - name: cherry-pick release commit
        run: |
          git checkout master
          git cherry-pick $NEW_TAG
      - name: craete pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore(release): ${{ env.NEW_TAG }}'
          branch: 'merge-release-${{ env.NEW_TAG }}'
